// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cans() {
  return window['go']['main']['App']['Cans']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CopyIP(arg1) {
  return window['go']['main']['App']['CopyIP'](arg1);
}

export function CopyMAC(arg1) {
  return window['go']['main']['App']['CopyMAC'](arg1);
}

export function DataFolder() {
  return window['go']['main']['App']['DataFolder']();
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function ExampleLayout() {
  return window['go']['main']['App']['ExampleLayout']();
}

export function Export() {
  return window['go']['main']['App']['Export']();
}

export function ImportLayout() {
  return window['go']['main']['App']['ImportLayout']();
}

export function InsertBlankAbove(arg1) {
  return window['go']['main']['App']['InsertBlankAbove'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function JSError(arg1) {
  return window['go']['main']['App']['JSError'](arg1);
}

export function Layout() {
  return window['go']['main']['App']['Layout']();
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function Redo() {
  return window['go']['main']['App']['Redo']();
}

export function SaveLayout(arg1) {
  return window['go']['main']['App']['SaveLayout'](arg1);
}

export function SetCheckForUpdates(arg1) {
  return window['go']['main']['App']['SetCheckForUpdates'](arg1);
}

export function SetMAC(arg1, arg2) {
  return window['go']['main']['App']['SetMAC'](arg1, arg2);
}

export function SetNextPosition(arg1, arg2) {
  return window['go']['main']['App']['SetNextPosition'](arg1, arg2);
}

export function SetNote(arg1, arg2) {
  return window['go']['main']['App']['SetNote'](arg1, arg2);
}

export function SetPosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPosition'](arg1, arg2, arg3);
}

export function Skip() {
  return window['go']['main']['App']['Skip']();
}

export function StartSession(arg1, arg2) {
  return window['go']['main']['App']['StartSession'](arg1, arg2);
}

export function State() {
  return window['go']['main']['App']['State']();
}

export function StopSession() {
  return window['go']['main']['App']['StopSession']();
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
