// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {site} from '../models';

export function Cans():Promise<Array<string>>;

export function CheckForUpdate():Promise<void>;

export function CopyIP(arg1:number):Promise<main.State>;

export function CopyMAC(arg1:number):Promise<main.State>;

export function Delete(arg1:number):Promise<main.State>;

export function Export():Promise<main.State>;

export function InsertBlankAbove(arg1:number):Promise<main.State>;

export function Layout():Promise<Array<site.Can>>;

export function OpenReleasePage():Promise<void>;

export function Redo():Promise<main.State>;

export function SaveLayout(arg1:Array<site.Can>):Promise<main.State>;

export function SetCheckForUpdates(arg1:boolean):Promise<void>;

export function SetMAC(arg1:number,arg2:string):Promise<main.State>;

export function SetNextPosition(arg1:number,arg2:number):Promise<main.State>;

export function SetNote(arg1:number,arg2:string):Promise<main.State>;

export function SetPosition(arg1:number,arg2:number,arg3:number):Promise<main.State>;

export function Skip():Promise<main.State>;

export function StartSession(arg1:string,arg2:number):Promise<main.State>;

export function State():Promise<main.State>;

export function StopSession():Promise<main.State>;

export function Undo():Promise<main.State>;

export function Version():Promise<string>;
